######################################################################
# Automatically generated by qmake (2.01a) ven. ao�t 21 10:09:26 2015
######################################################################

TEMPLATE = app
TARGET = simulator
DEPENDPATH += . 
INCLUDEPATH += .
LIBS += -lxml2 -lcrypto -lcryptopp -lssl
CONFIG += c++14
QMAKE_CXXFLAGS += --std=c++14 
CFLAGS+= -g -Wall

NS_BUILD_DIR =/home/diallo/simulator/ns3/ns-3-allinone/ns-3.30/build
#export LD_LIBRARY_PATH=/home/diallo/simulator/ns3/ns-3-allinone/ns-3.30/build/lib




LIBS += -L$$NS_BUILD_DIR/lib
INCLUDEPATH += $$NS_BUILD_DIR 

DEPENDPATH += $$BUILD_DIR

SHARED_LIB_FILES = $$files($$NS_BUILD_DIR/lib/*.so)
for(FILE, SHARED_LIB_FILES){
  BASENAME = $$basename(FILE)
  CLEARNAME = $$replace(BASENAME,libns,ns)
  CLEARNAME = $$replace(CLEARNAME,.so,)
  LIBS += -l$$CLEARNAME
}




# Input
DEFINES += NS3_LOG_ENABLE HAVE_SYS_IOCTL_H=1 HAVE_IF_NETS_H=1
DEFINES += HAVE_NET_ETHERNET_H=1 HAVE_PACKET_H=1
DEFINES += HAVE_IF_TUN_H=1

HEADERS += *.h   ../helper/*.h


SOURCES += *.cc  ../helper/*.cc
